---
- name: task 1 tomcat8 stop
  service: name=tomcat8 state=stopped
  become: true

- name: task 2 remove old files in webapps folder
  shell: rm -f /var/lib/tomcat8/webapps/*.war
  become: true
 
- name: remove old war file from staging area
  file: path=/tmp/sample.war state=absent
  become: true

- name: download war from cloud
  get_url: url=https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war dest=/tmp/sample.war
  become: true

- name: changemode 777 for war file
  file: path=/tmp/sample.war mode=0777
  become: true

- name: copy the war
  copy: src=/tmp/sample.war dest=/var/lib/tomcat8/webapps/sample.war
  become: true
  notify: tomcat8 starting
